"""empty message

Revision ID: 072d8d0ab7c7
Revises: 9b0cda08ebc2
Create Date: 2019-07-19 16:33:52.406018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072d8d0ab7c7'
down_revision = '9b0cda08ebc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'file', ['name'], unique=True)
    # ### end Alembic commands ###
