"""empty message

Revision ID: 081d111d9e3c
Revises: 6190ba287c6e
Create Date: 2019-08-01 16:25:11.763917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081d111d9e3c'
down_revision = '6190ba287c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('token', sa.String(length=150), nullable=True))
    op.drop_column('project', 'tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tokens', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('project', 'token')
    # ### end Alembic commands ###
