"""empty message

Revision ID: 0c625d67ef67
Revises: acc720d8d5b9
Create Date: 2019-08-29 11:03:27.689743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c625d67ef67'
down_revision = 'acc720d8d5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('startip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'startip')
    # ### end Alembic commands ###
