"""empty message

Revision ID: 134a6cbb4003
Revises: 2f8234141947
Create Date: 2019-08-02 16:58:15.588392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134a6cbb4003'
down_revision = '2f8234141947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('uuid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'uuid')
    # ### end Alembic commands ###
