"""empty message

Revision ID: 2883f7071ac6
Revises: 134a6cbb4003
Create Date: 2019-08-13 15:19:06.510191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2883f7071ac6'
down_revision = '134a6cbb4003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectuser', sa.Column('isAdmin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectuser', 'isAdmin')
    # ### end Alembic commands ###
