"""empty message

Revision ID: 2f8234141947
Revises: 081d111d9e3c
Create Date: 2019-08-02 15:47:28.155909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8234141947'
down_revision = '081d111d9e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dingmsg', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'dingmsg')
    # ### end Alembic commands ###
