"""empty message

Revision ID: 30af0c9ac9c8
Revises: 3992f26d6890
Create Date: 2019-08-01 16:10:16.470092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30af0c9ac9c8'
down_revision = '3992f26d6890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('token', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'token')
    # ### end Alembic commands ###
