"""empty message

Revision ID: 3992f26d6890
Revises: ed22aea66210
Create Date: 2019-08-01 11:27:11.577581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3992f26d6890'
down_revision = 'ed22aea66210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('repos_url', sa.String(length=50), nullable=True))
    op.drop_column('project', 'svn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('svn', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('project', 'repos_url')
    # ### end Alembic commands ###
