"""empty message

Revision ID: 6190ba287c6e
Revises: 30af0c9ac9c8
Create Date: 2019-08-01 16:25:06.018703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6190ba287c6e'
down_revision = '30af0c9ac9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tokens', sa.String(length=150), nullable=True))
    op.drop_column('project', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('token', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('project', 'tokens')
    # ### end Alembic commands ###
