"""empty message

Revision ID: 7fb816c84942
Revises: bbb4ac062759
Create Date: 2019-07-19 16:18:22.856696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb816c84942'
down_revision = 'bbb4ac062759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'username')
    # ### end Alembic commands ###
