"""empty message

Revision ID: 7fdbe293f886
Revises: 90f8f79fe427
Create Date: 2019-07-19 17:35:04.251575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fdbe293f886'
down_revision = '90f8f79fe427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('author', sa.String(length=50), nullable=True))
    op.drop_column('history', 'authora')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('authora', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('history', 'author')
    # ### end Alembic commands ###
