"""empty message

Revision ID: 82f4e349b72a
Revises: 072d8d0ab7c7
Create Date: 2019-07-19 16:37:58.966601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f4e349b72a'
down_revision = '072d8d0ab7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('localpaths', sa.String(length=150), nullable=True))
    op.drop_column('file', 'localpath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('localpath', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('file', 'localpaths')
    # ### end Alembic commands ###
