"""empty message

Revision ID: 84c94a86da69
Revises: ba46c22c2354
Create Date: 2019-07-19 17:34:19.965546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84c94a86da69'
down_revision = 'ba46c22c2354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('history', sa.Column('changed', sa.String(length=500), nullable=True))
    op.add_column('history', sa.Column('date', sa.DateTime(timezone=500), nullable=True))
    op.add_column('history', sa.Column('dirsChanged', sa.String(length=500), nullable=True))
    op.add_column('history', sa.Column('result', sa.String(length=500), nullable=True))
    op.add_column('history', sa.Column('youngest_revision', sa.String(length=50), nullable=True))
    op.drop_column('history', 'message')
    op.drop_column('history', 'serverId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('serverId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('history', sa.Column('message', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('history', 'youngest_revision')
    op.drop_column('history', 'result')
    op.drop_column('history', 'dirsChanged')
    op.drop_column('history', 'date')
    op.drop_column('history', 'changed')
    op.drop_column('history', 'author')
    # ### end Alembic commands ###
