"""empty message

Revision ID: 874c178d1962
Revises: c90bd64f9f54
Create Date: 2019-07-30 14:54:38.243010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874c178d1962'
down_revision = 'c90bd64f9f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectuser')
    # ### end Alembic commands ###
