"""empty message

Revision ID: 8defef1bfe68
Revises: 1e2339618ea2
Create Date: 2019-08-21 14:30:16.084842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8defef1bfe68'
down_revision = '1e2339618ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('userId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'userId')
    # ### end Alembic commands ###
