"""empty message

Revision ID: 8f5ea5bb0aa3
Revises: 57106c479ac1
Create Date: 2019-07-22 11:47:58.994291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5ea5bb0aa3'
down_revision = '57106c479ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'pname')
    # ### end Alembic commands ###
