"""empty message

Revision ID: 90f8f79fe427
Revises: 84c94a86da69
Create Date: 2019-07-19 17:34:47.654387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f8f79fe427'
down_revision = '84c94a86da69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('authora', sa.String(length=50), nullable=True))
    op.drop_column('history', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('history', 'authora')
    # ### end Alembic commands ###
