"""empty message

Revision ID: 9b0cda08ebc2
Revises: 7fb816c84942
Create Date: 2019-07-19 16:31:32.655792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0cda08ebc2'
down_revision = '7fb816c84942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('localpath', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'localpath')
    # ### end Alembic commands ###
