"""empty message

Revision ID: 9c8bf6125f18
Revises: b4d0b44ac132
Create Date: 2019-08-26 17:54:31.468108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8bf6125f18'
down_revision = 'b4d0b44ac132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('groupName', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'groupName')
    # ### end Alembic commands ###
