"""empty message

Revision ID: acc720d8d5b9
Revises: 8510a190a175
Create Date: 2019-08-28 16:12:00.538748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acc720d8d5b9'
down_revision = '8510a190a175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('file_id', sa.String(length=150), nullable=True))
    op.add_column('script', sa.Column('other', sa.String(length=50), nullable=True))
    op.drop_column('script', 'localpath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('localpath', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('script', 'other')
    op.drop_column('script', 'file_id')
    # ### end Alembic commands ###
