"""empty message

Revision ID: af2a18a6441e
Revises: 7fdbe293f886
Create Date: 2019-07-19 17:35:18.992688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2a18a6441e'
down_revision = '7fdbe293f886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dates', sa.DateTime(), nullable=True))
    op.drop_column('history', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('history', 'dates')
    # ### end Alembic commands ###
