"""empty message

Revision ID: ba46c22c2354
Revises: 82f4e349b72a
Create Date: 2019-07-19 16:38:09.798291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba46c22c2354'
down_revision = '82f4e349b72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('localpath', sa.String(length=150), nullable=True))
    op.drop_column('file', 'localpaths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('localpaths', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('file', 'localpath')
    # ### end Alembic commands ###
