"""empty message

Revision ID: bbb4ac062759
Revises: e22601d5a98e
Create Date: 2019-07-18 17:07:20.929481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbb4ac062759'
down_revision = 'e22601d5a98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('svn', sa.String(length=50), nullable=True))
    op.drop_column('project', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('address', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('project', 'svn')
    # ### end Alembic commands ###
