"""empty message

Revision ID: c90bd64f9f54
Revises: f59c874e6f5d
Create Date: 2019-07-23 15:52:38.350520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c90bd64f9f54'
down_revision = 'f59c874e6f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date', sa.String(length=50), nullable=True))
    op.drop_column('history', 'dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dates', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('history', 'date')
    # ### end Alembic commands ###
