"""packname

Revision ID: d66b245c3a40
Revises: aa533ea1af2e
Create Date: 2019-07-17 15:07:31.164233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66b245c3a40'
down_revision = 'aa533ea1af2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addsvn', sa.Column('packname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addsvn', 'packname')
    # ### end Alembic commands ###
