"""empty message

Revision ID: e22601d5a98e
Revises: d64f7a2a49e3
Create Date: 2019-07-18 17:06:16.786645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22601d5a98e'
down_revision = 'd64f7a2a49e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='project')
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=True)
    op.create_index('name', 'project', ['name'], unique=True)
    # ### end Alembic commands ###
