"""empty message

Revision ID: ebc3b2525d55
Revises: 5b97ab6a7231
Create Date: 2019-08-27 14:57:45.663754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc3b2525d55'
down_revision = '5b97ab6a7231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('Swtich', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('dingSwtich', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dingSwtich')
    op.drop_column('project', 'Swtich')
    # ### end Alembic commands ###
