"""empty message

Revision ID: ed22aea66210
Revises: 874c178d1962
Create Date: 2019-07-30 15:28:35.831148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed22aea66210'
down_revision = '874c178d1962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectuser', sa.Column('projectid', sa.Integer(), nullable=True))
    op.add_column('projectuser', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_column('projectuser', 'pid')
    op.drop_column('projectuser', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectuser', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('projectuser', sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('projectuser', 'userid')
    op.drop_column('projectuser', 'projectid')
    # ### end Alembic commands ###
