"""svn地址路径

Revision ID: ef2d1b0c8472
Revises: 8e94224522bf
Create Date: 2019-07-16 10:20:20.771288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef2d1b0c8472'
down_revision = '8e94224522bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('serverId', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('log', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('createTime', mysql.DATETIME(), nullable=True),
    sa.Column('updateTime', mysql.DATETIME(), nullable=True),
    sa.Column('isDelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('serverId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('log', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('base_model')
    # ### end Alembic commands ###
