"""empty message

Revision ID: f59c874e6f5d
Revises: 8f5ea5bb0aa3
Create Date: 2019-07-23 15:52:19.694235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f59c874e6f5d'
down_revision = '8f5ea5bb0aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('dates', sa.String(length=50), nullable=True))
    op.drop_column('history', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('history', 'dates')
    # ### end Alembic commands ###
